# Generated by Django 3.2.9 on 2021-11-22 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinksdata',
            name='date_posted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
